### ISSUE TITLE
Always on top이 종종 작동하지 않음

### ISSUE THREAD

**Issue by sH1222J** [organization/alspotron#1193]
.

**Comment by JellyBrick** [comment]
alspotron은 항상 모든 창 위에 표시되도록 되어있습니다.

**Comment by sH1222J** [comment]
아 디폴트되어있군요...
쓰다가 항상위가 풀리는경우가 종종 있더라구요...

**Comment by JellyBrick** [comment]
Ref: https://github.com/electron/electron/issues/2097#issuecomment-253420136

**Comment by mspakdel** [comment]
> ```ts
> setInterval(() => {
>   mainWindow.setAlwaysOnTop(true);
> }, 10000); 
> ```
> 
this code makes app window blink because i think its not fix the issue .
also i found this :
every time you open the youtube or similar apps and makes them fullscreen , the alwaysOnTop property changes and makes the window alwaysOnTop(false) 
this code:
```js
mainWindow.setAlwaysOnTop(true)
``` 
works fine until you change the onTop property of any app or window from OS point of view , it changes it to false again

**Comment by JellyBrick** [comment]
> > ```ts
> > setInterval(() => {
> >   mainWindow.setAlwaysOnTop(true);
> > }, 10000); 
> > ```
> 
> this code makes app window blink because i think its not fix the issue . also i found this : every time you open the youtube or similar apps and makes them fullscreen , the alwaysOnTop property changes and makes the window alwaysOnTop(false) this code:
> 
> ```js
> mainWindow.setAlwaysOnTop(true)
> ```
> 
> works fine until you change the onTop property of any app or window from OS point of view , it changes it to false again

What is the difference between this code and `alwaysOnTop: true`?

**Comment by mspakdel** [comment]
exactly i am saying this : there is no difference between two codes . because none of them didn't fix the issue. i told before it makes the window blink because every interval window gets alwaysontop and then goes down and makes the window blink. because from OS side the other app also gets alwaysontop and makes this window not be ontop again.
i think it must be fixed from OS side , because like GlobalShortcuts apps fights to be on top of others and this changes the ontop properties for all apps
